### ISSUE TITLE
Preprocessing mutation from WGS data for MutSigCV

### ISSUE THREAD

**Issue by ysbioinfo** [tgen/CovGen#3]
Hi
I am so grateful to you for developing such a convenient tool! But my data is from WGS, so my first question is, which bed file should I used in CovGen for WGS? 
An alternative way is to filter my mutations according to the default coverage table(exome_full192.coverage.txt). This maybe the fastest way. But if using that file, which type of mutation should be included in my input files for mutsig? In other words, when that table is created, which bed file is used? I note that there are many 'noncoding' effects in that table(exome_full192.coverage.txt), but in my opinion, exon = CDS + UTR; and intron shouldn't be included in exome, so is the 'noncoding' from UTR region? If so, for my WGS data, should I filtered out all mutations that are not in CDS or UTR regions?
Could you give me some advice? Thanks!

Best regards, 
Yang

**Comment by awchrist** [comment]
Hi Yang,
I appreciate your comment. 
I have not tried to run MutSig using variants derived from WGS data yet.
There are a few hardcoded limitations within MutSig itself that cause undesired results when it comes to WGS.
If I were to try, I would provide a bed file that is the start and stop for each gene in your gtf to at least get CovGen to work as it is today.
Then use the gene list and bed file output by CovGen to filter your maf file.

**Comment by ysbioinfo** [comment]
Thanks for your reply!
I have another question, if I use the exome_full192.coverage.txt as coverage file, should I filter out my mutations on intron and UTR before running MutSig?

**Comment by awchrist** [comment]
I would not filter out mutations purely based on if they are in the UTR or an intron. If you can find the targets of the capture kit the "exome_full192.coverage.txt" file was based on I would use those to help filter.
