### ISSUE TITLE
KeyError: 'chrY'

### ISSUE THREAD

**Issue by phuchoang1012** [tgen/CovGen#6]
Hello,

I am running CovGen to generate compatible coverage file for hg38:
/tools/CovGen-master/CovGen -o out -f GRCh38.fa -g Homo_sapiens.GRCh38.93.chr.gtf -t -t Exome-Agilent_V6_UTR_b38_merge.bed -s /apps/snpeff/4.3t/snpEff/ -v GRCh38.86

I encountered the following error:
Traceback (most recent call last):
  File "/tools/CovGen-master/getALTsForTargetsSeqsForMutSig.py", line 352, in <module>
    lseqs, lseqs_coord = parseBedFile(bedf, dict_fasta, naturalSortBedLoci)
  File "/tools/CovGen-master/getALTsForTargetsSeqsForMutSig.py", line 178, in parseBedFile
    logger.debug(id + " : " + str(len(dict_fasta[id])))
KeyError: 'chrY'

I wonder if you could offer some insights on this error and how to fix it. Thank you very much in advance for your help!

**Comment by awchrist** [comment]
Are you using a UCSC reference genome? UCSC uses "chr" in front of the chromosome.
If you  remove the "chr" from the reference fasta it should work.
