### ISSUE TITLE
Error: Found this base 'Pool' object has no attribute 'starmap' in Reference Genome; Aborting!

### ISSUE THREAD

**Issue by YonkoBigMom** [tgen/CovGen#7]
Hi,

I am running the following command:

./CovGen -o exome-v4 -f hs37d5.fa -g Homo_sapiens.GRCh37.74.gtf -t targets.bed -s /snpEff/ -v GRCh37.74 

getALTsForTargetsSeqsForMutSig.py 0.1

My targets.bed is like this

1       63193   63343   chr1:63194-63343
1       63441   63591   chr1:63442-63591
1       63622   63772   chr1:63623-63772
1       69436   69586   chr1:69437-69586
1       91461   91611   chr1:91462-91611
1       931286  931436  chr1:931287-931436

I ran into this error:

refGen: hs37d5.fa
bedfile:        exome-v4_GRCh37.74/exome-v4_GRCh37.74_step3b.bed
prefix: exome-v4_GRCh37.74/exome-v4_GRCh37.74_step4
cpus:   3
sort:   False

2019-01-07 19:34:43,104 [     INFO] - Parsing Reference Genome (assuming only 5 letters possible: A,C,G,T and N) ...
2019-01-07 19:37:20,932 [     INFO] - Parsing Reference Genome (assuming only 5 letters possible: A,C,G,T and N) ... DONE
2019-01-07 19:37:20,932 [     INFO] - Parsing bedfile (assuming no overlapping loci) ...
2019-01-07 19:37:21,878 [     INFO] - Parsing bedfile (assuming no overlapping loci) ... DONE
2019-01-07 19:37:21,878 [     INFO] - Processing Contigs for vcf header ...
2019-01-07 19:37:21,878 [     INFO] -   Sorting contigs ...
2019-01-07 19:37:21,882 [     INFO] -   Sorting contigs ... DONE
2019-01-07 19:37:21,882 [     INFO] - processing target sequences and capturing the ALTs ...
2019-01-07 19:37:22,279 [    ERROR] - WARNING: Base Not Found in our set of valid Base; Base should be A, C, G, T, or N; Check Reference Genome content for non-managed bases.
[ERROR/MainProcess] Found this base 'Pool' object has no attribute 'starmap' in Reference Genome; Aborting!

Would you please let me know how to fix it? Thanks.

**Comment by awchrist** [comment]
I believe this is related to the format of the targets, reference and gtf being inconsistent.
Your targets file uses the "chr" prefix for the chromosome. 
If the reference genome or the gtf do not use the "chr" prefix then you will get this error.

**Comment by YonkoBigMom** [comment]
Dear awchist,

Thanks for the reply. I pasted here the first few lines of the the target bed file, fa and gtf file. I think all three do not use "chr".  For some other purposes, in the target bed file, the "chr" was concatenated to form the ID (fourth field), but the first field was just number and X&Y. 

Do you have any suggestions?

**target file**

1 63193 63343 chr1:63194-63343
1 63441 63591 chr1:63442-63591
1 63622 63772 chr1:63623-63772
1 69436 69586 chr1:69437-69586
1 91461 91611 chr1:91462-91611
1 931286 931436 chr1:931287-931436

grep "^>" **hs37d5.fa**
>1 dna:chromosome chromosome:GRCh37:1:1:249250621:1
>2 dna:chromosome chromosome:GRCh37:2:1:243199373:1
>3 dna:chromosome chromosome:GRCh37:3:1:198022430:1
>4 dna:chromosome chromosome:GRCh37:4:1:191154276:1

head Homo_sapiens.GRCh37.74.gtf
1       processed_transcript    exon    11869   12227   .       +       .       gene_id "ENSG00000223972"; transcript_id "ENST00000456328"; exon_number "1"; gene_name "DDX11L1"; gene_biotype "pseudogene"; transcript_name "DDX11L1-002"; exon_id "ENSE00002234944";
1       processed_transcript    exon    12613   12721   .       +       .       gene_id "ENSG00000223972"; transcript_id "ENST00000456328"; exon_number "2"; gene_name "DDX11L1"; gene_biotype "pseudogene"; transcript_name "DDX11L1-002"; exon_id "ENSE00003582793";
1       processed_transcript    exon    13221   14409   .       +       .       gene_id "ENSG00000223972"; transcript_id "ENST00000456328"; exon_number "3"; gene_name "DDX11L1"; gene_biotype "pseudogene"; transcript_name "DDX11L1-002"; exon_id "ENSE00002312635";

**Comment by awchrist** [comment]
I apologize. Let's look at the "multiprocessing" module within python.
check the version of python you are using at the command line.
`python -V`
this should be 3.0 or greater.

now start python at the prompt
```
python
import multiprocessing
cpus=2
pool = multiprocessing.Pool(processes=cpus)  
pool.+tab
```
 
We are looking for the "pool.starmap(" attribute.
If it is not there lets try to upgrade the "multiprocessing" module.

**Comment by YonkoBigMom** [comment]
Thank you. I was using Python 2.7 (my bad!). Switching to python 3.6 and update multiprocessing solved it.

**Comment by YonkoBigMom** [comment]
Thank you. I was using Python 2.7 (my bad!). Switching to python 3.6 and update multiprocessing solved it.
